Improved logging
wasmbl/wasmbl pull request #64
Opened 2021-05-13 13:03 UTC by YohDeadfall

Closes #34.

2021-05-25 16:26 UTC, cecton requested changes

2021-05-25 16:26 UTC, cecton commented on src/lib.rs
> +                    warn!(
```suggestion
                    log::warn!(
```

Use the log crate directly so we don't have to maintain the list of imports up there.

2021-05-25 16:26 UTC, cecton commented on src/lib.rs
> +                            trace!("building SASS from {}", style_path.to_string_lossy());
This should be an INFO and it should be move to args's build_sass_from_dir.

* It needs to be an INFO because it's a useful information for the user to know what's going on. Sometimes you're just waiting and the terminal is silent. It's very annoying in wasm-run because of the lack of logs
* It needs to be in `build_sass_from_dir` because that method is part of the public API so the user might end up using it directly.

2021-05-25 16:26 UTC, cecton commented on src/lib.rs
> +    trace!("running pre-build hooks");
Make it info too

2021-05-25 16:26 UTC, cecton commented on src/lib.rs
> +    trace!("running post-build hooks");
info

2021-05-30 14:21 UTC, cecton commented on src/lib.rs
> +        log::trace!("building SASS from {}", input_dir.to_string_lossy());
You need to use the display function to avoid unnecessary allocation

2021-05-30 14:21 UTC, cecton commented on src/lib.rs
> +    log::trace!("running pre-build hooks");
I think is one hook so it should be singular?

2021-05-30 14:21 UTC, cecton commented on src/lib.rs
> +    log::trace!("running post-build hooks");
One hook actually?

2021-05-30 14:21 UTC, cecton commented on src/lib.rs
>          "Development server started: http://{}:{}",
The other logs start with a lower case character but this one with a capital letter. Choose one convention and apply it everywhere (where it makes sense)

2021-05-30 15:22 UTC, YohDeadfall commented on src/lib.rs
>          "Development server started: http://{}:{}",
I usually see output starting with a capital letter, but `bail!` and `expect` use lower case for everything not only here. What is a canonical style for messages?

2021-05-31 04:19 UTC, cecton commented on src/lib.rs
>          "Development server started: http://{}:{}",
I think for errors its best to use lowercase (bail, expect, error Display).

For log lines it's just a matter of taste. I know that doesn't help but tbh I don't care that much, I only care about consistency

2021-05-31 04:22 UTC, cecton commented on src/lib.rs
> +        log::trace!("building SASS from {}", input_dir.to_string_lossy());
Avoid log::trace and use log::info instead. Trace is useful for debugging but the point of this issue is to inform the user what they are waiting for. This log for instance deserves to be info

2021-05-31 05:57 UTC, YohDeadfall commented on src/lib.rs
> +        log::trace!("building SASS from {}", input_dir.to_string_lossy());
Argh, forgot to replace it. Will do.

2021-06-01 09:45 UTC, cecton commented
```
[1] [09:42:04] ~/r/w/e/frontend-only logging > c run -- serve
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `/home/cecile/repos/wasmbl/target/debug/frontend-only serve`
[2021-06-01T09:42:17Z INFO  wasmbl] Building frontend package
[2021-06-01T09:42:17Z INFO  wasmbl] Running pre-build hook
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
[2021-06-01T09:42:17Z WARN  walrus::module] failed to parse `name` custom section Invalid name type (at offset 3267815)
[2021-06-01T09:42:17Z INFO  wasmbl] Running post-build hook
[2021-06-01T09:42:17Z INFO  wasmbl] Development server started: http://127.0.0.1:3000
[2021-06-01T09:42:17Z INFO  tide::server] Server listening on http://127.0.0.1:3000
```
Almost good!

1. Apparently we get the logs of all crates... so we have the "server listening" twice. We can simply remove ours.

2. There is a warning about walrus we should fix. I have no idea what it is.

3. We should consider if we actually want to display the logs of other crates like that. I think it is possible to disable. Maybe it's good to keep. I don't know... this is something to think about.

4. The "pre-build" log comes after the "build" log but then we see build logs. This makes no sense. Probably they are misplaced.

2021-06-01 09:46 UTC, cecton commented on src/lib.rs
> +    log::info!("Running pre-build hook");
You can see that the `command` is created before we run the pre-build hook but the command is actually run AFTER. That is why your logs are misplaced.

2021-06-01 09:47 UTC, cecton commented on src/lib.rs
> +    log::info!("Running pre-build hook");
("pre-build" does mean it is ran before build genius :grin: )

2021-06-01 09:49 UTC, YohDeadfall commented on src/lib.rs
> +    log::info!("Running pre-build hook");
Then the next should be moved too since it executes the hook after build, sound like a bug 🤔

2021-06-01 09:53 UTC, YohDeadfall commented on src/lib.rs
> +    log::info!("Building frontend package");
I see misunderstanding. This line says that building is started in general, but for someone it might mean that `cargo` started. Move it after the pre-hook?

2021-06-01 09:57 UTC, YohDeadfall commented on src/lib.rs
>      let status = command.status().context("could not start build process")?;
Otherwise, this line should have a special log message.

2021-06-01 11:32 UTC, cecton commented on src/lib.rs
> +    log::info!("Building frontend package");
Ah right. It's "frontend package" :thinking: yes it's a misunderstanding then. I think we should improve it. The frontend needs to be compiled so for me that is a more important information than "build a frontend package". Also we don't really put a package, we prepare the build directory, it can be not packaged at all

2021-06-01 11:33 UTC, cecton commented on src/lib.rs
>      let status = command.status().context("could not start build process")?;
Yes I think I would prefer the log here that says "Compiling frontend..." or something like that. This is the most important part after all

2021-06-02 07:39 UTC, YohDeadfall commented on src/lib.rs
> +    log::info!("Building frontend");
Moved the message here instead of adding `Compiling frontend`. Without  indentation 4 messages don't look well, and it feels like `Building frontend` and `Compiling frontend` are the same. Therefore, only three `Running pre-build hook`, `Building frontend` and `Running post-build hook`.

2021-06-02 12:07 UTC, cecton approved these changes

2021-06-02 12:07 UTC, merged